

variables:
  username: $(USERNAME) # Common username for APIC Connect, stored securely
  password: $(PASSWORD) # Common password for APIC Connect, stored securely
  artifactory_url:  # Artifactory URL

stages:
- stage: APICLogin
  displayName: API Connect Login
  jobs:
  - job: DownloadAndSetup
    displayName: Download APIC Binary and Setup
    steps:
    - script: |
        echo "Downloading apic-mac from Artifactory..."
        curl -u $(ARTIFACTORY_USER):$(ARTIFACTORY_TOKEN) -O $(artifactory_url)/apic-mac
        echo "Moving apic-mac to ApicScripts folder..."
        mv apic-mac ./ApicScripts/apic-mac
        chmod +x ./ApicScripts/apic-mac
      displayName: Download and Prepare APIC Binary

  - job: LoginToAPIC
    dependsOn: DownloadAndSetup
    displayName: Login to API Connect
    steps:
    - script: |
        chmod +x ./ApicScripts/apic_login.sh
        ./ApicScripts/apic_login.sh dev $(username) $(password)
      displayName: Login to Dev Environment in APIC
    - script: |
        ./ApicScripts/apic_login.sh sit $(username) $(password)
  
